### ISSUE TITLE
feature request: Implement delay

### ISSUE THREAD

**Issue by BertRijsdijk** [tickls/proxickls#2]
I'dd like to be able to set a delay in the responses as a way to be able to control the order in which responses are returned. (e.g. for asynchronous testing)

The way I see it there could be a separate endpoint e.g. a POST to /proxy/setDelay and post the delay in ms. The response of the listed calls would be delayed wether or not the response is manipulate.

An array of requests would be perfect if possible :-)
```json 
{
  "delay": [
    {
      "url": "/oauth/token",
      "delay": 2500
    },
    {
      "url": "/mobile/dashboard/84151105208",
      "delay": 0
    }
  ]
}
```

**Comment by ronaldw** [comment]
Picking this up. Think I can do it as my first NodeJS feature ever :P.

**Comment by ronaldw** [comment]
Done! I unfortunately cannot push my branch as I not have write access :+1:

**Comment by tickls** [comment]
I implemented it in an easier/simpler way, but merged ronald his branch now
